---
- name: Deploy Streamlit App Locally
  hosts: local
  #become: yes
  tasks:
    - name: Ensure Python3 and pip are installed (Debian-based systems)
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - python3
        - python3-pip
      when: ansible_os_family == "Debian"

    - name: Copy app.py to local home directory
      copy:
        src: app.py
        dest: "/home/bhuvana_1234/app.py"
        mode: "0755"

    - name: Copy requirements.txt to local home directory
      copy:
        src: requirements.txt
        dest: "/home/bhuvana_1234/requirements.txt"
        mode: "0644"

    - name: Install Python packages from requirements.txt
      pip:
        requirements: "/home/bhuvana_1234/requirements.txt"
        executable: pip3

    - name: Run Streamlit app in the background using full path
      shell: |
        nohup /usr/bin/env streamlit run /home/bhuvana_1234/app.py > /home/bhuvana_1234/streamlit.log 2>&1 &
      args:
        executable: /bin/bash
