name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install streamlit
        pip install pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    
    #- name: Test with pytest
     # run: |
      #  pytest -v  # Running pytest with verbose output for debugging
    
    - name: Install Node.js and npm
      run: |
        curl -sL https://deb.nodesource.com/setup_16.x | bash -
        sudo apt-get install -y nodejs

    - name: Install Vercel CLI
      run: |
        npm install -g vercel
    
    - name: Deploy to Vercel
      run: |
        vercel --prod --yes --token ${{ secrets.VERCEL_TOKEN }}
      env:
        VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
